# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Je1Vh7SusXxljsJSXIYBpZ4M_MhrZpIo
"""

# 1. Install the required libraries (This runs automatically in Colab)
!pip install groq gradio -q
from google.colab import userdata
userdata.get('Altanta')
import os
import gradio as gr
from groq import Groq
from google.colab import userdata

# 2. Fetch your API key securely from Colab Secrets
# (Make sure you have added a secret named 'GROQ_API_KEY' in the left sidebar!)
try:
    os.environ["GROQ_API_KEY"] = userdata.get('Altanta')
except userdata.SecretNotFoundError:
    print("Error: Please set GROQ_API_KEY in the Colab Secrets tab (the key icon on the left)!")

# 3. Initialize the Groq Client
client = Groq()

# 4. Define the function that processes the chat
def chatbot_response(message, history):
    # Start with a system prompt to tell the AI how to behave
    messages = [{"role": "system", "content": "You are a helpful and friendly AI assistant."}]

    # Format the chat history so Groq understands the context of the conversation
    for human_text, ai_text in history:
        messages.append({"role": "user", "content": human_text})
        messages.append({"role": "assistant", "content": ai_text})

    # Add the user's newest message
    messages.append({"role": "user", "content": message})

    # Call the Groq API using your specified model
    chat_completion = client.chat.completions.create(
        messages=messages,
        model="llama-3.3-70b-versatile",
    )

    # Return the text generated by the model
    return chat_completion.choices[0].message.content

# 5. Build and Launch the Gradio User Interface
demo = gr.ChatInterface(
    fn=chatbot_response,
    title="Altanta her by Groq",
    description="Powered by Llama 3.3 (70B) via Groq API.",
    theme="soft",
)

# Launch the app! (debug=True helps show any errors in the Colab output)
demo.launch(debug=True)